# Alacritty Configuration

[general]
live_config_reload = true

[scrolling]
history = 10000

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "On" }

[window]
padding = { x = 10, y = 10 }

# Catppuccin Mocha theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B[13;2u"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
mode = "~Vi"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"
